apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "krank.fullname" . }}-config
  labels:
    {{- include "krank.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
data:
  scale-config: |
    {{ .Values.scaleConfig | toYaml | nindent 4 }}

  {{- if and (.Values.kafkaCert) (ne .Values.kafkaCert "") }}
  kafka-cert: |
    {{ .Values.kafkaCert | nindent 4 }}
  {{- end }}
