apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "krank.fullname" . }}-role
  labels:
    {{- include "krank.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["*"]
    resources: ["deployments", "services", "deployments/scale", "services/scale"]
    verbs:
      - "get"
      - "list"
      - "watch"
      - "update"
      - "patch"
      - "delete"
      - "create"
