apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "krank.fullname" . }}-rolebinding
  labels:
    {{- include "krank.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
subjects:
    - kind: ServiceAccount
      name: {{ include "krank.serviceAccountName" . }}
      namespace: {{ .Release.Namespace }}
roleRef:
    kind: Role
    name: {{ include "krank.fullname" . }}-role
    apiGroup: rbac.authorization.k8s.io
